### ISSUE TITLE
‘grattanCharts’ is not available (for R version 3.4.1)

### ISSUE THREAD

**Issue by carmelachivers1** [HughParsonage/grattanCharts#3]
Running install.packages("grattanCharts") produces an error: 

Warning in install.packages :
  package ‘grattanCharts’ is not available (for R version 3.4.1). 

Is this an issue on my end?

**Comment by HughParsonage** [comment]
Not on CRAN. Try devtools::install_github("hughparsonage/grattanCharts")

**Comment by carmelachivers1** [comment]
Thanks!
