### ISSUE TITLE
Adding Brisbane Coastline

### ISSUE THREAD

**Issue by DianaHourani** [HughParsonage/grattanCharts#5]
Hi Hugh

I was hoping to add a brisbane coastine to Grattan Charts. The code is below: 

```r
Brisbane_coastline <- 
  Australian_coastline %>%
  .[lat %between% c(-28.14, -26.79)] %>%
  .[long %between% c(150.0, 153.40)]  %>%
  # Islands cause difficulties
  .[, N := .N, by = group] %>%
  .[N == max(N)] %>%
  .[, c("group", "N", "rowname", "hole", "piece", "id") := NULL]
```

But i think Hugh B mentioned to you that a strange line comes up when i use the above code. Any ideas why?

**Comment by HughParsonage** [comment]
Thanks for the report. In this case, you'll probably need to retain the `piece` component of the coastline data to distinguish Bribie Island from the mainland.

```r
Brisbane_coastline <- 
  Australian_coastline %>%
  .[lat %between% c(-28.14, -26.79)] %>%
  .[long %between% c(150.0, 153.40)]  %>%
  # Islands cause difficulties
  .[, N := .N, by = group] %>%
  .[N == max(N)]

Brisbane_coastline %>%
  ggplot(aes(x = long, y = lat, 
             order = order,
             group = interaction(piece, group))) +
  geom_path() +
  coord_map()
```

![image](https://user-images.githubusercontent.com/8111628/41343624-725fcaf4-6f42-11e8-97ed-b1c6ec886014.png)

**Comment by DianaHourani** [comment]
Thanks - it's worked now. That was really helpful.
